# // Route du back rajouter dashboard a chaque route qui passe par le back

dashboard:
  controller: Dashboard
  action: board

# // Routes de l'authentification
register:
  controller: Auth
  action: register

verify_account:
  controller: Auth
  action: verifyAccount

login:
  controller: Auth
  action: login

forgot_password:
  controller: Auth
  action: pwdforgot

new_pass:
  controller: Auth
  action: change

logout:
  controller: Auth
  action: logout

# // Routes Pages 
create-page:
  controller: Page
  action: create

# // Routes Articles
create-article:
  controller: Article
  action: create

# // Routes Users
dashboard/users:
  controller: UserCrud
  action: index

dashboard/users-create:
  controller: UserCrud
  action: create

dashboard/users-update:
  path: users-update
  controller: UserCrud
  action: edit

dashboard/users-delete:
  path: /users-delete
  controller: UserCrud
  action: delete


# // Routes du Front

default:
  controller: Main
  action: home

home:
  controller: Main
  action: home

about-us:
  controller: Main
  action: aboutUs

page:
  controller: Page
  action: index

article:
  controller: Article
  action: index



