default:
  controller: Auth
  action: login
  
# Page du dashboard
dashboard:
  controller: Dashboard
  action: board

# Page utilisateur du dashboard
utilisateur:
  controller: Dashboard
  action: users

a-propos:
  controller: Main
  action: aboutUs

about-us:
  controller: Main
  action: aboutUs

contact:
  controller: Main
  action: contact

login:
  controller: Auth
  action: login

logout:
  controller: Auth
  action: logout

register:
  controller: Auth
  action: register

new_pass:
  controller: Auth
  action: change

#Accueil 

accueil:
  controller: Main
  action: home
