default:
  controller: Auth
  action: login


dashboard:
  controller: Dashboard
  action: board

a-propos:
  controller: Main
  action: aboutUs

about-us:
  controller: Main
  action: aboutUs

contact:
  controller: Main
  action: contact

login:
  controller: Auth
  action: login

logout:
  controller: Auth
  action: logout

register:
  controller: Auth
  action: register

  #rajouter une page avec fonctionnalité :
  #verifier dans la bdd s'il y a un enregistrement dans page dont le nom de la page est ... (le sleug)

test:
  controller: page
  action: show

dashboard_1:
  controller: Main
  action: home
