default:
  controller: Auth
  action: login

dashboard:
  controller: Dashboard
  action: board

a-propos:
  controller: Main
  action: aboutUs

about-us:
  controller: Main
  action: aboutUs

contact:
  controller: Main
  action: contact

login:
  controller: Auth
  action: login

logout:
  controller: Auth
  action: logout

register:
  controller: Auth
  action: register

accueil:
  controller: Main
  action: home

users:
  controller: UserCrud
  action: index
