# // Routes de l'authentification

register:
  controller: Auth
  action: register

verify_account:
  controller: Auth
  action: verifyAccount

login:
  controller: Auth
  action: login

reset_password:
  controller: Auth
  action: pwdforgot

reset_password_email:
  controller: Auth
  action: pwdforgot_with_email

new_pass:
  controller: Auth
  action: change

logout:
  controller: Auth
  action: logout

# Page du dashboard
dashboard:
  controller: Dashboard
  action: board

# Page utilisateur du dashboard
utilisateur:
  controller: Dashboard
  action: users

a-propos:
  controller: Main
  action: aboutUs

about-us:
  controller: Main
  action: aboutUs

contact:
  controller: Main
  action: contact

login:
  controller: Auth
  action: login

logout:
  controller: Auth
  action: logout

register:
  controller: Auth
  action: register

new_pass:
  controller: Auth
  action: change

create-page:
  controller: Page
  action: create

create-article:
  controller: Article
  action: create


# // Routes du Front

default:
  controller: Main
  action: home

home:
  controller: Main
  action: home

about-us:
  controller: Main
  action: aboutUs

page:
  controller: Page
  action: index

article:
  controller: Article
  action: index

# // Commentaire

comments:
  controller: CommentController
  action: commentController  

reportComment:
  controller: CommentController
  action: reportComment
  method: POST

# // CommentCrud

commentaires:
  controller: CommentCrud
  action: index

commentaires-delete:
  path: /commentaires-delete
  controller: CommentCrud
  action: delete

commentaires-approve:
  path: /commentaires-approve
  controller: CommentCrud
  action: approve

# // Formulaire commentaire

comment: 
  controller: Auth
  action: comment


# // Routes Users
dashboard/users:
  controller: UserCrud
  action: index

dashboard/users-create:
  controller: UserCrud
  action: create

dashboard/users-update:
  path: users-update
  controller: UserCrud
  action: edit

dashboard/users-delete:
  path: /users-delete
  controller: UserCrud
  action: delete

