# // Route du back
default:
  controller: Auth
  action: login

dashboard:
  controller: Dashboard
  action: board

login:
  controller: Auth
  action: login

logout:
  controller: Auth
  action: logout

register:
  controller: Auth
  action: register

new_pass:
  controller: Auth
  action: change


# // Routes du Front
home:
  controller: Main
  action: home

about-us:
  controller: Main
  action: aboutUs

contact:
  controller: Main
  action: contact

page:
  controller: Page
  action: index

create-page:
  controller: Page
  action: create

article:
  controller: Article
  action: index

create-article:
  controller: Article
  action: create

