# // Route du back
default:
  controller: Main
  action: home

dashboard:
  controller: Dashboard
  action: board

login:
  controller: Auth
  action: login

logout:
  controller: Auth
  action: logout

register:
  controller: Auth
  action: register

new_pass:
  controller: Auth
  action: change

create-page:
  controller: Page
  action: create

create-article:
  controller: Article
  action: create


# // Routes du Front
home:
  controller: Main
  action: home

about-us:
  controller: Main
  action: aboutUs

contact:
  controller: Main
  action: contact

page:
  controller: Page
  action: index

article:
  controller: Article
  action: index

# // Commentaire

comments:
  controller: CommentController
  action: commentController  

reportComment:
  controller: CommentController
  action: reportComment
  method: POST

# // CommentCrud

commentaires:
  controller: CommentCrud
  action: index

commentaires-delete:
  path: /commentaires-delete
  controller: CommentCrud
  action: delete

commentaires-approve:
  path: /commentaires-approve
  controller: CommentCrud
  action: approve


# // UserCrud
users:
  controller: UserCrud
  action: index

users-create:
  controller: UserCrud
  action: create

users-update:
  path: users-update
  controller: UserCrud
  action: edit

users-delete:
  path: /users-delete
  controller: UserCrud
  action: delete


comment: 
  controller: Auth
  action: comment

